export enum actionTypes {
  FETCH_REPOSITORIES_REQUEST = 'FETCH_REPOSITORIES_REQUEST',
  FETCH_REPOSITORIES_SUCCESS = 'FETCH_REPOSITORIES_SUCCESS',
  FETCH_REPOSITORIES_ERROR = 'FETCH_REPOSITORIES_ERROR',
  FETCH_CONTRIBUTORS_REQUEST = 'FETCH_CONTRIBUTORS_REQUEST',
  FETCH_CONTRIBUTORS_SUCCESS = 'FETCH_CONTRIBUTORS_SUCCESS',
  FETCH_CONTRIBUTORS_ERROR = 'FETCH_CONTRIBUTORS_ERROR'
}